### ISSUE TITLE
Desktop build for current target should not pass --target

### ISSUE THREAD

**Issue by thomcc** [mozilla/rust-android-gradle#10]
E.g. on darwin we shouldn't pass --target=x86_64-apple-darwin. Doing prevents us from reusing anything in either sccache or cargo's dep cache.

**Comment by ncalexan** [comment]
Mmm.  I vaguely recall doing this for consistency.  It's especially annoying 'cuz the names and directory structure of Cargo's output change with and without an explict `--target`.  But you're absolutely right, we should not pass `--target` for the current target.
