### ISSUE TITLE
Cannot find rustc command

### ISSUE THREAD

**Issue by hmmmk** [mozilla/rust-android-gradle#102]
I'm trying to build Shadowsocks application which uses rust-android-gradle and I'm always facing the same error with finding rustc. Can you tell me what am I doing wrong and how can I fix it?

Here is error message:

` 1: Task failed with an exception.
   What went wrong:
   Execution failed for task ':core:cargoBuildArm'.
   A problem occurred starting process 'command 'rustc''
`

P.S.: I'm using MacOS and when I'm trying to access rustc from terminal everything works fine

**Comment by ncalexan** [comment]
By default, we're going to `exec` a bare `rustc`.  Configure your `$PATH` as appropriate or override directly: https://github.com/ncalexan/rust-android-gradle/blob/master/README.md#specifying-paths-to-sub-commands-python-cargo-and-rustc.
