### ISSUE TITLE
build only for phone target

### ISSUE THREAD

**Issue by lattice0** [mozilla/rust-android-gradle#107]
Currently, when I do `flutter run`, it builds for both x86_64 and aarch64, even though the phone will only use the aarch64 .so lib. Of course for publishing the app this is desired but is it possible to make rust-android-gralde compile the target architecture?

This slows down testing a lot

**Comment by ncalexan** [comment]
Yes: there is a single `cargoBuild` job that depends on the architecture-specific `cargoBuild{$ARCH}` jobs; you have probably wired the `cargoBuild` job into your task graph.  Set up your Gradle tasks to depend on the arch-specific jobs.  (No idea how to achieve that with Flutter but it can't be that hard.)

Alternatively, use [`local.properties` to restrict the built architectures during testing](https://github.com/mozilla/rust-android-gradle#specifying-local-targets).
