### ISSUE TITLE
Failed to sync gradle after apply rust plugin

### ISSUE THREAD

**Issue by Gaurav-pix** [mozilla/rust-android-gradle#111]
What i Did...

1. Added the ->
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'org.mozilla.rust-android-gradle:plugin:0.9.3'
    }
}

to top build.gradle(Project:AppName)

2. set plugin inside build.gradle(Module:App)

plugins {
    id 'org.mozilla.rust-android-gradle.rust-android'
}

-> Expected behaviour properly sync and compile project
-> Actual behaviour got error saying "A problem occurred configuring project ':app'.> module cannot be null"

I'm new to this so any help would be appreciated. I'm not sure what went wrong

**Comment by ncalexan** [comment]
Just in case anybody sees this -- I expect that [`module`](https://github.com/mozilla/rust-android-gradle/blob/master/README.md#module) was not set in the `cargo` block.
