### ISSUE TITLE
compile failed with -target=aarch64-linux-android

### ISSUE THREAD

**Issue by tyrionchen** [mozilla/rust-android-gradle#124]
Why am I able to successfully compile when I run cargo build in the rust directory, but it fails when I add --target=aarch64-linux-android? 
Here are the steps I took:

`git clone git@github.com:mozilla/rust-android-gradle.git`
`rustup target add aarch64-linux-android`
`cd rust-android-gradle/samples/rust`

and this compiled successfully:
`cargo build`
<img width="880" alt="image" src="https://user-images.githubusercontent.com/42833301/231639510-4c6424ad-cb85-43aa-adc5-d370df77b292.png">

this compiled failed:
`cargo build --target=aarch64-linux-android`
<img width="892" alt="image" src="https://user-images.githubusercontent.com/42833301/231639603-912fe372-ad20-4849-8e38-7411adfdf8a7.png">

The error message told me that target aarch64-linux-android is not installed, but I have already installed it.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/42833301/231640303-8e91f2cf-69cd-4075-8546-372a792f4f2d.png">

**Comment by ncalexan** [comment]
I suggest running Gradle with `--info` or `--verbose`.  Then you should be able to see the full `cargo` command lines executed.  My guess is that Gradle is finding a different installation than that on your shell path, but there's only one way to find out.

**Comment by tyrionchen** [comment]
> I suggest running Gradle with `--info` or `--verbose`. Then you should be able to see the full `cargo` command lines executed. My guess is that Gradle is finding a different installation than that on your shell path, but there's only one way to find out.

Thanks for @ncalexan 's reply. The cause of this issue has been identified, and I will close this issue for now. 
Let me explain. I initially discovered this issue when I failed to build the cargo module using the org.mozilla.rust-android-gradle.rust-android plugin. After analyzing the code, I found that it would always fail as long as we ran "cargo build" with the "--target" parameter. So I raised this question on URLO and eventually got some help, which helped me solve the problem. For those who encounter this issue, you can refer to this link: https://users.rust-lang.org/t/compile-failed-with-target-aarch64-linux-android/92439

**Comment by tyrionchen** [comment]
> I suggest running Gradle with `--info` or `--verbose`. Then you should be able to see the full `cargo` command lines executed. My guess is that Gradle is finding a different installation than that on your shell path, but there's only one way to find out.

thanks @ncalexan, you are right

**Comment by ncalexan** [comment]
Glad you got to the bottom of things, and thanks for the helpful link to the thread where you resolved the issue!
