### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "librust.so" not found

### ISSUE THREAD

**Issue by opfromthestart** [mozilla/rust-android-gradle#127]
I am trying to do a simple example at https://github.com/opfromthestart/openfunny.
No matter what I do, I always get this error when running the application. The .so files appear in both the rust/target and app/build/rustJniLibs directories, but it always gives this error. I am new to android development and have had no success for multiple hours.

**Comment by opfromthestart** [comment]
I found a workaround by running `./gradlew installDebug` but I would prefer a solution that works with closer to default Android Studio.

**Comment by SergioRibera** [comment]
@opfromthestart You have to specify the `targetDirectory` as this is because the `rustJniLibs` folder is empty, this is better explained [here](https://github.com/mozilla/rust-android-gradle/issues/109#issuecomment-1185718077), but in summary add this

```groovy
cargo {
  // ...
  targetDirectory = "../path/to/target/"
}
```

> **Note:** If you have problems with the `libc++_shared` library, add [this](https://github.com/mozilla/rust-android-gradle/issues/106#issuecomment-1246687230) to your `build.gradle`

**Comment by kirillzh** [comment]
For what it's worth, we started seeing the same issue with Android Gradle Plugin 7.4.2+. AGP 7.4.0 worked fine.

**Comment by opfromthestart** [comment]
The files are being copied fine 
![image](https://github.com/mozilla/rust-android-gradle/assets/13816619/167033b0-f0d9-4742-a996-907cc36858ab)
but it still gives the error that it cannot find librust.so

**Comment by kirillzh** [comment]
This workaround seemed to work for me https://github.com/mozilla/rust-android-gradle/issues/118#issuecomment-1569407058

**Comment by opfromthestart** [comment]
That still does not work. I updated the repo to reflect my changes

**Comment by opfromthestart** [comment]
I fixed it by changing "cdylib" to "staticlib" and "dylib"
