### ISSUE TITLE
Linking fails with Python 3.13 (`pipes` has been removed)

### ISSUE THREAD

**Issue by StuartHarris** [mozilla/rust-android-gradle#153]
Since Python 3.13, `pipes` is no longer available (see [here](https://peps.python.org/pep-0594/)), so linking fails on this line: https://github.com/mozilla/rust-android-gradle/blob/c62655cae09dc7b7540e96a07d35881f18ce4251/plugin/src/main/resources/com/nishtahir/linker-wrapper.py#L4

**Comment by Rawa** [comment]
@ncalexan Any plans on fixing this? currently broken with latest python 😢

**Comment by ncalexan** [comment]
Sorry for the long delay; this project is not even close to the top of my list these days :)

Fixed by #156.
