### ISSUE TITLE
Replace ncalexan by mozilla in the gradle plugin portal ?

### ISSUE THREAD

**Issue by martinbonnin** [mozilla/rust-android-gradle#18]
https://plugins.gradle.org/plugin/org.mozilla.rust-android-gradle.rust-android points to https://github.com/ncalexan/rust-android-gradle which hasn't been active since April. The mozilla repository where I'm entering an issue right now seems to be the repository that uploads artifacts. Can this be clarified ?

**Comment by ncalexan** [comment]
If it's possible to do so, I don't see it.  The Gradle Plugin Portal is not well loved, AFAICT, so it's possible there's no UI for that.  (I tried a few days ago, too.)

**Comment by ncalexan** [comment]
I take that back!  It's in the publication data: https://github.com/mozilla/rust-android-gradle/blob/master/plugin/build.gradle#L51-L52.

@thomcc next time you cut a release, let's bump these.  Thanks for the prod, @martinbonnin.

**Comment by thomcc** [comment]
Fixed in 0.8.3
