### ISSUE TITLE
Can I use this also as an non-android jni library?

### ISSUE THREAD

**Issue by deeprobin** [mozilla/rust-android-gradle#23]
If yes, how? If no, how?

**Comment by ncalexan** [comment]
> If yes, how? If no, how?

Hi @deeprobin: sorry for the very delayed reply.  Pretty much all of the functionality here assumes that the Rust being built is compiled using an Android NDK -- i.e., most of the subtle bits are around configuring `CC`/`CXX`/`AR` etc for the prebuilt NDK clang toolchain.  Most of the remaining functionality has to do with wiring tasks into the `com.android.*` Gradle plugin.  My guess is that with effort you could extract the Cargo-specific pieces, but at that point you probably just want to start a new plugin.  (And such a plugin might exist already.)

So I'm going to say no, it's not possible, and in fact it's probably an anti-goal of this plugin to support non-Android usages.  That said, the basic method will apply and you could either learn or copy code and layout from this example.
