### ISSUE TITLE
Sample App Incorrect or Out of Date

### ISSUE THREAD

**Issue by drkstr101** [mozilla/rust-android-gradle#25]
https://github.com/mozilla/rust-android-gradle/blob/16a12c2dd20fb9a7bc35cf6c5f813f65b49d775d/samples/app/build.gradle#L39

Hello,

I believe the referenced line should read `libname = "rust"`. According to the README, *targetIncludes* defaults to *["lib${libname}.so", "lib${libname}.dylib", "{$libname}.dll"]*, making the lib prefix reduntant.

Until I made this change locally, the sample app was not correctly linking `librust.so` in the apk, leading to a bit of confusion getting started. Otherwise works like a charm.

Cheers, and thanks for your time!

**Comment by ncalexan** [comment]
Thanks for the report, and sorry for the slow reply!  I'm largely not touching this at this time but I'd gladly take a PR to apply.

**Comment by drkstr101** [comment]
No problem, thanks for the reply! PR sent. Cheers!

**Comment by ncalexan** [comment]
Better late than never, right?  :)
