### ISSUE TITLE
CargoBuild error without any message

### ISSUE THREAD

**Issue by bigdogs** [mozilla/rust-android-gradle#44]
Hi, I compile failed with the following message, but there is no useful  error message. 

> Task :app:generateToolchains
Toolchain for arch arm version 21 exists: checked /var/folders/rr/7h6c2bdd259_k2thf7m_phnh0000gn/T/rust-android-ndk-toolchains/arm-21
Toolchain for arch arm64 version 21 exists: checked /var/folders/rr/7h6c2bdd259_k2thf7m_phnh0000gn/T/rust-android-ndk-toolchains/arm64-21
Toolchain for arch x86 version 21 exists: checked /var/folders/rr/7h6c2bdd259_k2thf7m_phnh0000gn/T/rust-android-ndk-toolchains/x86-21
Toolchain for arch x86_64 version 21 exists: checked /var/folders/rr/7h6c2bdd259_k2thf7m_phnh0000gn/T/rust-android-ndk-toolchains/x86_64-21

> Task :app:cargoBuildArm FAILED
7 actionable tasks: 6 executed, 1 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildArm'.
> A problem occurred starting process 'command 'cargo''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 638ms
4:27:44 PM: Task execution finished 'build'.

**Comment by bigdogs** [comment]
with --stacktrace flags, it says that "no such file",
 does anyone knowns how to resolve this ? 
thanks in advance

![image](https://user-images.githubusercontent.com/20614926/93707418-f25f8580-fb60-11ea-98ee-81b27bcd2b95.png)
![image](https://user-images.githubusercontent.com/20614926/93707421-04d9bf00-fb61-11ea-88ed-9a85ccc3b917.png)

**Comment by bigdogs** [comment]
with --stacktrace flags added, it says that "No such file or directory" for cargo, Does anyone knows how to resolve this?

**Comment by bigdogs** [comment]
Solution still not found, but another plugin "https://github.com/willir/cargo-ndk-android-gradle" works for me.

issue closed

**Comment by ncalexan** [comment]
For the next person, you can set `rust.cargoCommand` in your `local.properties`, or an environment variable, or mangle your path: see https://github.com/ncalexan/rust-android-gradle/blob/master/README.md#specifying-paths-to-sub-commands-python-and-cargo.

> Solution still not found, but another plugin "https://github.com/willir/cargo-ndk-android-gradle" works for me.

Just for your own info, we're thinking of promoting that plugin to "top of the stack" -- see the discussion in #40.  I'm glad that plugin is working for you!

**Comment by Progdrasil** [comment]
I'm having the same issue, Unfortunately i cannot use the other gradle plugin as I cannot create Desktop builds to run my unit tests.
I've tried setting the `rust.cargoCommand` to `/usr/bin/cargo` and `/home/user/.cargo/bin/cargo` and neither work.

**Comment by ncalexan** [comment]
@Progdrasil lots of logs and information about your configuration will be needed for us to get started tracking things down for you.  Can you start by attaching `./gradlew --debug` logs?

**Comment by Osniackal** [comment]
I had the same issue. I first tried to specify the cargo path, where it said `Process 'command '/Users/{myname}/.cargo/bin/cargo'' finished with exit value -1 (state: FAILED)`. Running with --debug showed me the actual error, which was that my working_dir specified via `module  = "../rust"` was invalid.

The solution for me was to specify it like this: `module = "../../rust"` as my project structure looked like this:

`./android/app/build.gradle`
`./rust_project/cargo.toml`

**Comment by Scramjet911** [comment]
> I had the same issue. I first tried to specify the cargo path, where it said `Process 'command '/Users/{myname}/.cargo/bin/cargo'' finished with exit value -1 (state: FAILED)`. Running with --debug showed me the actual error, which was that my working_dir specified via `module = "../rust"` was invalid.
> 
> The solution for me was to specify it like this: `module = "../../rust"` as my project structure looked like this:
> 
> `./android/app/build.gradle` `./rust_project/cargo.toml`

Had the same issue, path was wrong. Thank you! 

Maybe a check before the cargo build process with an error might make it clearer though?
