### ISSUE TITLE
Incompatible with Gradle 7

### ISSUE THREAD

**Issue by nekohasekai** [mozilla/rust-android-gradle#60]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':shadowsocks:cargoBuildArm' (type 'CargoBuildTask').
  - Type 'com.nishtahir.CargoBuildTask' property 'toolchain' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**Comment by ncalexan** [comment]
Thanks for the report, @nekohasekai.  Right now the set of Gradle/Android-Gradle plugin versions supported is *very* limited,  but I have some work-in-progress to make this better and to start testing them: https://github.com/ncalexan/rust-android-gradle/tree/citest.  I hope to get back to this soon and this work will allow the plugin to work with Gradle 7.

**Comment by Mygod** [comment]
Please fix this as Android gradle plugin 7.0.0-beta04 requires Gradle 7.0.2 now. Thank you!

**Comment by davidhewitt** [comment]
I just had a go with the `citest` branch locally and it seems to work well with Gradle 7! Thanks for your continued maintenance of this plugin! 🚀

**Comment by Morgawr** [comment]
Is there any progress on this? I've been trying to build rust bindings for some android app and this effectively kills my project as there's no way I can figure out to work around gradle 7 requirements

**Comment by ncalexan** [comment]
> Is there any progress on this? I've been trying to build rust bindings for some android app and this effectively kills my project as there's no way I can figure out to work around gradle 7 requirements

@Morgawr not really -- I haven't had time to push this any further.  You could test the citest branch locally, which I hope to get back to Any Day Now.  David Hewitt might be able to give more instruction on how they set it up -- it should be standard but Gradle can be fiddly.

**Comment by davidhewitt** [comment]
I'm not a gradle expert, and this was a few weeks ago, so it's possible the below is incorrect.

What I think I did:
 - cloned this repo
 - checked out the `citest` branch
 - built it using Gradle 7 (and JDK 11) using the development instructions here: https://github.com/mozilla/rust-android-gradle#development
- use my locally built copy as per config from https://github.com/mozilla/rust-android-gradle#real-projects

It seems to be working fine on Android Studio 2020.3.1 with Gradle 7.

**Comment by Mygod** [comment]
Could you do a release regardless to fix this issue? This is becoming urgent.

**Comment by ncalexan** [comment]
> Could you do a release regardless to fix this issue? This is becoming urgent.

There's a reason I haven't released this and it's because it needs more work.  However, perfect is the enemy of the good, and I imagine that a semver 0.9 (or 1.0) release would let people roll back.  Or perhaps I can tag a release candidate so that consumers have to opt in?  I will investigate as I can.

**Comment by ncalexan** [comment]
In theory, the v0.9.0 I just pushed release/publish on should work with more versions of Java, Gradle, and the Android-Gradle Plugin.  It has a rudimentary CI framework taken wholesale from https://github.com/gradle/android-cache-fix-gradle-plugin that should help us narrow down specific issues.  I monkeyed with the publishing so I wouldn't be surprised if it will take a few tries to get it published correctly -- let me know if I've messed up the Maven coordinates, etc.

Testing very much appreciated!

**Comment by davidhewitt** [comment]
It seems to be working well with Android Studio 2020.3.1 and Gradle 7.1, thanks!

A heads up that the classpath listed on https://plugins.gradle.org/plugin/org.mozilla.rust-android-gradle is different to the one shown in the README.

**Comment by ncalexan** [comment]
> It seems to be working well with Android Studio 2020.3.1 and Gradle 7.1, thanks!
> 
> A heads up that the classpath listed on https://plugins.gradle.org/plugin/org.mozilla.rust-android-gradle is different to the one shown in the README.

Thanks, @davidhewitt.  I've filed and hopefully fixed https://github.com/mozilla/rust-android-gradle/issues/70 for this.  I didn't mean to change coordinates, but the publishing details changed.

**Comment by Mygod** [comment]
Thanks. It seems to be working quite well with AGP 7.0.2. (I have delayed the upgrade due to another bug in AGP...)
