### ISSUE TITLE
Target was x86 but had to install i686 target as well in order to get library to compile

### ISSUE THREAD

**Issue by corjohnson** [mozilla/rust-android-gradle#61]
Hello, I have been trying to get a simple hello world jni rust program up and running, but I kept running into weird errors (usually gradle just crashing as it tried to launch cargo). 

```
System info: 
Windows 10 64-bit
Intel CPU
rust-android-gradle plugin version: "0.8.6"
rustc version: rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

In the module's gradle file I had the target set up as: 

```groovy
cargo {
    module = "../../hello"
    libname = "hello"
    targets = ["x86"]
}
```

And with `rustup target` I had: `x86_64-linux-android (installed)`.

I was only ever to get my app to run/compile after I added

`i686-linux-android (installed)`

I'm not entirely sure why this is the case? This seems like a bug but maybe it's just my misunderstanding. I just wanted to flag it in case others are having similar issues

**Comment by corjohnson** [comment]
Ah wait; I am clearly too tired. I needed to put `"x86_64"`, sorry! Closing

**Comment by ncalexan** [comment]
> Ah wait; I am clearly too tired. I needed to put `"x86_64"`, sorry! Closing

Glad you found the right incantation.  There are so many options to choose from when naming architectures; since I expect folks using this plugin to be familiar with the Android-Gradle plugin conventions, I used the same names: `x86`, `x86_64`, etc.
