### ISSUE TITLE
How to use locally

### ISSUE THREAD

**Issue by lattice0** [mozilla/rust-android-gradle#65]
I want to contribute to this plugin in order to solve https://github.com/mozilla/rust-android-gradle/issues/63 however I'm quite lost on how to use the plugin locally so I can modify things. 

According to the readme I should do

```
buildscript {
    repositories {
        maven {
            url "file:///Users/nalexander/Mozilla/rust-android-gradle/samples/maven-repo"
        }
    }

    dependencies {
        classpath 'org.mozilla.rust-android-gradle:plugin:0.3.0'
    }
}
```

but to get something inside `maven-repo` I need to run `./gradlew publish`, is this it?

I get

```
root@a6a0feb0184b:/home/dev/orwell/flutter_orwell_app/android# gradle assembleDebug

FAILURE: Build failed with an exception.

* Where:
Build file '/home/dev/orwell/flutter_orwell_app/android/rust_android_gradle/plugin/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating project ':rust_android_gradle:plugin'.
> Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt
```

and I also tested other methods of using plugins locally, but they all give this error

**Comment by lucaszanella** [comment]
Sorry, the error above is not the true one. It worked, however it looks like I need to do `./gradlew publish` on every modification. Isn't there a simpler way to just point to the source and get it compiled for me so I can do lots of modifications and see if it works on my project? How do people develop gradle plugins locally?

I tried to find a way on the web like in here: https://stackoverflow.com/a/56161288/10116440 but then I get the actual error `> Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt`

**Comment by ncalexan** [comment]
@lattice0 I've added some notes in the README about using the sample apps directly, and made them run in CI, so that we can be confident they continue working.  You can also use the `dependencySubstitution` approach documented in the README.
