### ISSUE TITLE
When will we release the next tag?

### ISSUE THREAD

**Issue by pfchen** [mozilla/rust-android-gradle#66]
I find tag v0.8.6 has a critical bug, but this bug has been fixed by this commit: https://github.com/mozilla/rust-android-gradle/commit/aff8cdb1fbb9d28469cff98ab6c5ed60a764e12c

**Comment by ncalexan** [comment]
> I find tag v0.8.6 has a critical bug, but this bug has been fixed by this commit: [aff8cdb](https://github.com/mozilla/rust-android-gradle/commit/aff8cdb1fbb9d28469cff98ab6c5ed60a764e12c)

I didn't expect that to be a critical anything.  I've pushed v0.8.7, assuming the publishing CI action succeeds it should be in the plugins queue shortly.  Testing appreciated!

**Comment by ncalexan** [comment]
Looks like this published, so I'm closing this.  File follow-up if I made an error.

**Comment by pfchen** [comment]
Thank you very much for your quick reply and the new tag v0.8.7 fixed my problem.

Sorry for not being clear. If we use v0.8.6 and set `apiLevels` like this:
```groovy
apiLevels = [
    "arm": 16,
    "x86": 16,
    "x86_64": 21,
    "arm64": 21,
]
```

`rust-android-gradle` plugin will generate `CLANG_PATH` like this:

```sh
CLANG_PATH=/path/to/prebuilt/ndk/bin/armv7a-linux-androideabi16-clang
CLANG_PATH=/path/to/prebuilt/ndk/bin/i686-linux-android16-clang
CLANG_PATH=/path/to/prebuilt/ndk/bin/x86_64-linux-android16-clang
CLANG_PATH=/path/to/prebuilt/ndk/bin/aarch64-linux-android16-clang
```

But the minimum API level for Android 64-bit architectures is 21, so there is no `x86_64-linux-android16-clang` and `aarch64-linux-android16-clang` in the ndk directory to build targets `x86_64` and `arm64` respectively.


This bug has troubled me for some time. Thanks again!

**Comment by ncalexan** [comment]
You're welcome.  You should really thank @dcsommer, who did the good work to actually address the issue :)
