### ISSUE TITLE
Support for Apple M1 aarch64 

### ISSUE THREAD

**Issue by skhamis** [mozilla/rust-android-gradle#77]
Application-services is currently running into an issue with compiling NSS via rust-android-gradle https://github.com/mozilla/application-services/issues/4665.

I believe it's potentially something to do with `rust-android-gradle` associating Darwin = x86_64 https://github.com/mozilla/application-services/issues/4665#issuecomment-984161587 which works if the Mac is using a JDK = x86_64 but M1's are now defaulting to downloading arm64 (homebrew) JDKs which causes the builds to break.

We probably need to allow the ability for Darwin to = arm64

**Comment by ncalexan** [comment]
@skhamis thanks for the report.  As we discussed on Slack, I'm not aware of any fundamental blocker to making this work.  My expectation is that we need to split `darwin` into `darwin-{x86-64,aarch64}`.  We do run some tests in CI these days, but I'm not sure that we can target macOS aarch64 machines in Github Actions, nor am I sure that we're running any Robolectric style tests.

Let me know how you get on with a patch.  Thanks!

**Comment by skhamis** [comment]
@ncalexan I think it the PR ended up being pretty straightforward! To keep things straightforward and prevent anyone from breaking too bad. I decided to go with keeping `darwin` and simply adding `darwin-x86-64` and `aarch64` as new targets to keep things moving. At some point I can make a PR to remove the `darwin` target once the dust has settled a bit and seems to be stable.

**Comment by ncalexan** [comment]
This landed and is, I believe, working well for [application-services](https://github.com/mozilla/application-services/blob/cbfa39d756f63e95bd76b8efdbb1907eb1c368e6/build.gradle#L24).
