### ISSUE TITLE
Expose `AR_...=llvm-ar` with Android NDK 23+ toolchains

### ISSUE THREAD

**Issue by montekki** [mozilla/rust-android-gradle#91]
I am trying to build a project that has `ring` as a dependency that uses `cc-rs` which among other things requires invoking custom `CC` and `AR`s among other things.

Since [r23](https://github.com/android/ndk/wiki/Changelog-r23) GNU binutils including stuff like `x86_64-linux-android-ar` have been removed so what I am trying to do is to point the build to the `llvm-ar` like this:

```
cargo {
	targets = ["x86_64"]
	apiLevel = 21
	exec { spec, toolchain ->
		if (toolchain.target == "x86_64-linux-android") {
			spec.environment("AR_x86_64_linux_android", "llvm-ar")
		}
	}
}
```

But apparently it has no effect and falls back with an error message 

```
error occurred: Failed to find tool. Is `/home/$USER/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar` installed?

```

**Comment by ncalexan** [comment]
Hmm, interesting.  So the `exec` block should impact those variables for the actual invocation, but it won't impact the checking by the `rust-android-gradle` plugin itself -- and that's what you're seeing.

It rather sounds like we need to accommodate these changes to NDK 23+ in https://github.com/mozilla/rust-android-gradle/blob/5bfc241fee3043991351105ddaa562f6b46afa77/plugin/src/main/kotlin/com/nishtahir/RustAndroidPlugin.kt#L110-L152.  Patches wanted!

**Comment by montekki** [comment]
I was able to solve this with specifying an absolute path to ndk's `llvm-ar`

```gradle
exec { spec, toolchain ->
	if (toolchain.target == "x86_64-linux-android") {
		spec.environment("AR_x86_64-linux-android", "$ndkDir/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar")
	}
	if (toolchain.target == "armv7-linux-androideabi") {
		spec.environment("AR_armv7-linux-androideabi", "$ndkDir/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar")
	}
	if (toolchain.target == "aarch64-linux-android") {
		spec.environment("AR_aarch64-linux-android", "$ndkDir/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar")
	}
}
```

**Comment by montekki** [comment]
> I added it to the cargo block in my build.gradle file, but the error is still there

check out our gradle file [here](https://github.com/paritytech/parity-signer/blob/f7dd2aca790e5952e89182e9ff470d222f8b8738/android/app/build.gradle#L62)

**Comment by ncalexan** [comment]
This should be fixed in the just published 0.9.3.  Testing appreciated!

**Comment by Will5** [comment]
It seems the llvm-ar error is resolved, but now I am getting an lgcc error:
```
  = note: ld: error: unable to find library -lgcc
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
The release notes mention lgcc, so perhaps it is related.

**Comment by ncalexan** [comment]
> I created a [secret gist](https://gist.github.com/Will5/b5924e4329214ac6433784f825e47932)

Well, this is a first: those logs _strongly_ suggest that you're building with `cargo ndk`, which isn't this plugin.  In particular, you'll need the equivalent of #83 in your setup.

**Comment by Will5** [comment]
> > I created a [secret gist](https://gist.github.com/Will5/b5924e4329214ac6433784f825e47932)
> 
> Well, this is a first: those logs _strongly_ suggest that you're building with `cargo ndk`, which isn't this plugin. In particular, you'll need the equivalent of #83 in your setup.

You're right. I see someone added cargoNdk as a dependency of another task. I'm not sure what the solution is, but we can stay on NDK 22.
